data-location = "/Users/nacho/.nuvlaedge/data/"
config-location = "/etc/nuvlaedge"

[logging]
debug = false
level = "info"
log-path = "/var/log/nuvlaedge"
log-file = "nuvlaedge.log"
log-max-size = 100
log-max-backups = 3

[agent]
nuvlaedge-uuid = "nuvlabox/5c67543b-8165-4902-b4bb-9c4d23a48abe"
nuvla-endpoint = "https://nuvla.io"
nuvla-insecure = false
telemetry-period = 60
heartbeat-period = 20
api-key = ""
api-secret = ""
log-level = "info"
log-to-file = true

[agent.commissioner]
period = 60
log-level = "info"
log-to-file = true

[agent.telemetry]
period = 60
log-level = "info"
log-to-file = true

[agent.vpn]
period = 60
enabled = true
interface-name = "vpn0"
extra-config = ""
log-level = "info"
log-to-file = true

[system-manager.mqtt]
port = 1883
host = "localhost"

[system-manager.system-requirements]
cpu = 0.5
memory = 512
disk = 5
docker-version = ">=1.13.1"
k8s-version = ">=1.10.0"
