name: "CI Static Analysis"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
          cache: true

      - name: "Install GoSec"
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: "Run tests"
        run: |
          make ci/test/cover
          make ci/sec

      - name: "SonarCloud Update"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
