on:
  workflow_dispatch:

jobs:
  qgate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
          cache: true

      - name: "Install GoSec"
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: "Run tests"
        run: |
          make ci/test
          make ci/lint
          make ci/sec
      
      
        
